import type { GalleryImage } from "@/lib/galleryPreview";

/** Remaining gallery photos — loaded only after the user clicks Load more. */
export const GALLERY_EXTRA: GalleryImage[] = [
  { url: "/images/gallery/007.jpg", alt: "Pupa Restaurant interior" },
  { url: "/images/gallery/008.jpg", alt: "Guests at Pupa" },
  { url: "/images/gallery/009.jpg", alt: "Dining at Pupa Restaurant" },
  { url: "/images/gallery/010.jpg", alt: "Mediterranean food at Pupa" },
  { url: "/images/gallery/011.jpg", alt: "Pupa Restaurant atmosphere" },
  { url: "/images/gallery/012.jpg", alt: "Evening at Pupa" },
  { url: "/images/gallery/013.jpg", alt: "Charcoal grill dishes at Pupa" },
  { url: "/images/gallery/014.jpg", alt: "Wine and dining at Pupa" },
  { url: "/images/gallery/015.jpg", alt: "Tomahawk steaks at Pupa" },
  { url: "/images/gallery/016.jpg", alt: "Guests at Pupa" },
  { url: "/images/gallery/017.jpg", alt: "Dining at Pupa Restaurant" },
  { url: "/images/gallery/018.jpg", alt: "Mediterranean food at Pupa" },
  { url: "/images/gallery/019.jpg", alt: "Pupa Restaurant atmosphere" },
  { url: "/images/gallery/020.jpg", alt: "Evening at Pupa" },
  { url: "/images/gallery/021.jpg", alt: "Pupa wine corks" },
  { url: "/images/gallery/022.jpg", alt: "Wine and dining at Pupa" },
  { url: "/images/gallery/023.jpg", alt: "Pupa Restaurant interior" },
  { url: "/images/gallery/024.jpg", alt: "Guests at Pupa" },
  { url: "/images/gallery/025.jpg", alt: "Dining at Pupa Restaurant" },
  { url: "/images/gallery/026.jpg", alt: "Mediterranean food at Pupa" },
  { url: "/images/gallery/027.jpg", alt: "Candlelit stairs at Pupa" },
  { url: "/images/gallery/028.jpg", alt: "Evening at Pupa" },
  { url: "/images/gallery/029.jpg", alt: "Charcoal grill dishes at Pupa" },
  { url: "/images/gallery/030.jpg", alt: "Wine and dining at Pupa" },
  { url: "/images/gallery/031.jpg", alt: "Pupa Restaurant interior" },
  { url: "/images/gallery/032.jpg", alt: "Guests at Pupa" },
  { url: "/images/gallery/033.jpg", alt: "Dining at Pupa Restaurant" },
  { url: "/images/gallery/034.jpg", alt: "Mediterranean food at Pupa" },
  { url: "/images/gallery/035.jpg", alt: "Pupa Restaurant atmosphere" },
  { url: "/images/gallery/036.jpg", alt: "Evening at Pupa" },
  { url: "/images/gallery/037.jpg", alt: "Charcoal grill dishes at Pupa" },
  { url: "/images/gallery/038.jpg", alt: "Wine and dining at Pupa" },
  { url: "/images/gallery/039.jpg", alt: "Pupa Restaurant interior" },
  { url: "/images/gallery/040.jpg", alt: "Guests at Pupa" },
  { url: "/images/gallery/041.jpg", alt: "Dining at Pupa Restaurant" },
  { url: "/images/gallery/042.jpg", alt: "Mediterranean food at Pupa" },
  { url: "/images/gallery/043.jpg", alt: "Pupa Restaurant atmosphere" },
  { url: "/images/gallery/044.jpg", alt: "Evening at Pupa" },
  { url: "/images/gallery/045.jpg", alt: "Charcoal grill dishes at Pupa" },
  { url: "/images/gallery/046.jpg", alt: "Wine and dining at Pupa" },
  { url: "/images/gallery/047.jpg", alt: "Pupa Restaurant interior" },
  { url: "/images/gallery/048.jpg", alt: "Guests at Pupa" },
  { url: "/images/gallery/049.jpg", alt: "Dining at Pupa Restaurant" },
  { url: "/images/gallery/050.jpg", alt: "Mediterranean food at Pupa" },
];
