import type { GalleryImage } from "@/lib/galleryPreview";

/** Remaining gallery photos — loaded only after the user clicks Load more. */
export const GALLERY_EXTRA: GalleryImage[] = [
  { url: "/images/gallery/06.jpg", alt: "Mediterranean flavours" },
  { url: "/images/gallery/07.jpg", alt: "Wine and dining at Pupa" },
  { url: "/images/gallery/08.png", alt: "Pupa Restaurant & Bar" },
  { url: "/images/gallery/09.jpg", alt: "Mediterranean tapas" },
  { url: "/images/gallery/10.jpg", alt: "Dining at Pupa Manchester" },
  { url: "/images/gallery/11.jpg", alt: "Restaurant interior" },
  { url: "/images/gallery/12.png", alt: "Evening at Pupa" },
  { url: "/images/gallery/13.jpg", alt: "Grilled meats" },
  { url: "/images/gallery/14.jpg", alt: "Pupa kitchen" },
  { url: "/images/gallery/15.png", alt: "Celebration at Pupa" },
  { url: "/images/gallery/16.png", alt: "Private dining" },
  { url: "/images/gallery/17.png", alt: "Manchester Northern Quarter" },
  { url: "/images/gallery/18.png", alt: "Mediterranean grill" },
  { url: "/images/gallery/19.jpg", alt: "Charcoal grill at Pupa" },
  { url: "/images/gallery/20.jpg", alt: "Seasonal dishes" },
  { url: "/images/gallery/21.jpg", alt: "Pupa Restaurant food" },
  { url: "/images/gallery/22.jpg", alt: "Lunch at Pupa" },
  { url: "/images/gallery/23.jpg", alt: "Meat selection" },
  { url: "/images/gallery/24.jpg", alt: "Party at Pupa" },
  { url: "/images/gallery/25.jpg", alt: "Private hire" },
  { url: "/images/gallery/26.jpg", alt: "Pupa outside restaurant" },
  { url: "/images/gallery/27.jpg", alt: "Steak carousel" },
  { url: "/images/gallery/28.jpg", alt: "Mediterranean tapas spread" },
  { url: "/images/gallery/29.jpg", alt: "Tapas selection" },
  { url: "/images/gallery/30.jpg", alt: "Pupa hero dining room" },
  { url: "/images/gallery/31.jpg", alt: "Restaurant ambience" },
  { url: "/images/gallery/32.jpg", alt: "Dining experience" },
  { url: "/images/gallery/33.jpg", alt: "Pupa evening service" },
  { url: "/images/gallery/34.jpg", alt: "Mediterranean evening" },
  { url: "/images/gallery/35.jpg", alt: "Pupa team and guests" },
  { url: "/images/gallery/36.jpg", alt: "Northern Quarter restaurant" },
  { url: "/images/gallery/37.jpg", alt: "Pupa signature dishes" },
  { url: "/images/gallery/38.jpg", alt: "Weekend dining" },
  { url: "/images/gallery/39.jpg", alt: "Dessert and coffee" },
];
